[package]
name = "yunlink-rust-advanced-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.34.3"
egui = "0.34.3"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time"] }
yunlink = { path = "../../bindings/rust/yunlink" }
yunlink-sys = { path = "../../bindings/rust/yunlink-sys" }

[[bin]]
name = "yunlink-rust-advanced-monitor"
path = "src/main.rs"
