if (NOT DEFINED ROOT_DIR)
  set(ROOT_DIR "@ROOT_DIR@")
endif()

function(assert_exists relpath)
  if (NOT EXISTS "${ROOT_DIR}/${relpath}")
    message(FATAL_ERROR "missing required file: ${relpath}")
  endif()
endfunction()

function(assert_file_contains relpath needle)
  file(READ "${ROOT_DIR}/${relpath}" content)
  string(FIND "${content}" "${needle}" offset)
  if (offset EQUAL -1)
    message(FATAL_ERROR "expected '${needle}' in ${relpath}")
  endif()
endfunction()

assert_exists(".clang-format")
assert_exists(".clang-tidy")
assert_exists(".gitmodules")
assert_exists("CMakePresets.json")
assert_exists("docs/protocol/README.md")
assert_exists("docs/bindings/test-matrix.md")
assert_exists("docs/protocol/integration-guide.md")
assert_exists("docs/protocol/scenario-walkthroughs.md")
assert_exists("docs/protocol/implementation-status.md")
assert_exists("docs/protocol/migration-notes.md")
assert_exists("tools/build_fast.py")
assert_exists("tools/run_clang_format.sh")
assert_exists("tools/check_clang_format.sh")
assert_exists("tools/run_clang_tidy.sh")

assert_file_contains(".gitmodules" "path = thirdparty/asio")
assert_file_contains(".gitmodules" "url = https://github.com/chriskohlhoff/asio.git")
assert_file_contains("CMakePresets.json" "\"ninja-debug\"")
assert_file_contains("CMakePresets.json" "\"ninja-release\"")
assert_file_contains("CMakePresets.json" "\"ci-ninja\"")
assert_file_contains("CMakePresets.json" "\"generator\": \"Ninja\"")
assert_file_contains("CMakeLists.txt" "add_custom_target(clang-format")
assert_file_contains("CMakeLists.txt" "add_custom_target(clang-format-check")
assert_file_contains("CMakeLists.txt" "add_custom_target(clang-tidy")
assert_file_contains("CMakeLists.txt" "add_custom_target(lint")
assert_file_contains("README.md" "cmake --preset ninja-debug")
assert_file_contains("README.md" "python3 tools/build_fast.py --preset ninja-debug")
assert_file_contains("README.md" "docs/protocol/README.md")
assert_file_contains("README.md" "docs/protocol/integration-guide.md")
assert_file_contains("README.md" "docs/protocol/scenario-walkthroughs.md")
assert_file_contains("README.md" "docs/protocol/implementation-status.md")
assert_file_contains("docs/bindings/test-world-map.md" "test-matrix.md")
assert_file_contains("docs/bindings/test-matrix.md" "covered-in-repo")
assert_file_contains("docs/bindings/test-matrix.md" "blocked-external")
assert_file_contains("docs/protocol/README.md" "yunlink-protocol-spec.md")
assert_file_contains("docs/protocol/README.md" "integration-guide.md")
assert_file_contains("docs/protocol/README.md" "scenario-walkthroughs.md")
assert_file_contains("docs/protocol/README.md" "implementation-status.md")
assert_file_contains("docs/protocol/README.md" "migration-notes.md")

message(STATUS "development tooling integration is present")
