<?xml version="1.0"?>
<package format="2">
  <name>sunray_yunlink_compare_ui</name>
  <version>0.0.1</version>
  <description>UI tool for comparing Sunray ROS topics with received Yunlink snapshots.</description>

  <maintainer email="1369013252@qq.com">ddiquan</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>mavros_msgs</build_depend>
  <build_depend>sunray_msgs</build_depend>

  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>nav_msgs</build_export_depend>
  <build_export_depend>mavros_msgs</build_export_depend>
  <build_export_depend>sunray_msgs</build_export_depend>

  <exec_depend>roscpp</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>mavros_msgs</exec_depend>
  <exec_depend>sunray_msgs</exec_depend>

  <export/>
</package>
