# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: org.yunlink.shell/v1/shell.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'org.yunlink.shell/v1/shell.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n org.yunlink.shell/v1/shell.proto\x12\x14org.yunlink.shell.v1\".\n\x10ShellOpenRequest\x12\x0c\n\x04\x63ols\x18\x01 \x01(\r\x12\x0c\n\x04rows\x18\x02 \x01(\r\"\xb5\x01\n\x11ShellOpenResponse\x12/\n\x05\x65rror\x18\x01 \x01(\x0e\x32 .org.yunlink.shell.v1.ShellError\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0bsession_uid\x18\x03 \x01(\t\x12\x19\n\x11output_stream_uid\x18\x04 \x01(\t\x12\x12\n\nshell_name\x18\x05 \x01(\t\x12\x0c\n\x04\x63ols\x18\x06 \x01(\r\x12\x0c\n\x04rows\x18\x07 \x01(\r\"6\n\x11ShellWriteRequest\x12\x13\n\x0bsession_uid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"m\n\x12ShellWriteResponse\x12/\n\x05\x65rror\x18\x01 \x01(\x0e\x32 .org.yunlink.shell.v1.ShellError\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rbytes_written\x18\x03 \x01(\r\"E\n\x12ShellResizeRequest\x12\x13\n\x0bsession_uid\x18\x01 \x01(\t\x12\x0c\n\x04\x63ols\x18\x02 \x01(\r\x12\x0c\n\x04rows\x18\x03 \x01(\r\"s\n\x13ShellResizeResponse\x12/\n\x05\x65rror\x18\x01 \x01(\x0e\x32 .org.yunlink.shell.v1.ShellError\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ols\x18\x03 \x01(\r\x12\x0c\n\x04rows\x18\x04 \x01(\r\"(\n\x11ShellCloseRequest\x12\x13\n\x0bsession_uid\x18\x01 \x01(\t\"f\n\x12ShellCloseResponse\x12/\n\x05\x65rror\x18\x01 \x01(\x0e\x32 .org.yunlink.shell.v1.ShellError\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06\x63losed\x18\x03 \x01(\x08*\x8e\x02\n\nShellError\x12\x1b\n\x17SHELL_ERROR_UNSPECIFIED\x10\x00\x12\x0c\n\x08SHELL_OK\x10\x01\x12\x12\n\x0eSHELL_DISABLED\x10\x02\x12\x19\n\x15SHELL_INVALID_REQUEST\x10\x03\x12\x0e\n\nSHELL_BUSY\x10\x04\x12\x1b\n\x17SHELL_SESSION_NOT_FOUND\x10\x05\x12\x1a\n\x16SHELL_SESSION_MISMATCH\x10\x06\x12\x15\n\x11SHELL_NOT_RUNNING\x10\x07\x12\x1b\n\x17SHELL_PERMISSION_DENIED\x10\x08\x12\x15\n\x11SHELL_UNAVAILABLE\x10\t\x12\x12\n\x0eSHELL_IO_ERROR\x10\nb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'org.yunlink.shell.v1.shell_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHELLERROR']._serialized_start=792
  _globals['_SHELLERROR']._serialized_end=1062
  _globals['_SHELLOPENREQUEST']._serialized_start=58
  _globals['_SHELLOPENREQUEST']._serialized_end=104
  _globals['_SHELLOPENRESPONSE']._serialized_start=107
  _globals['_SHELLOPENRESPONSE']._serialized_end=288
  _globals['_SHELLWRITEREQUEST']._serialized_start=290
  _globals['_SHELLWRITEREQUEST']._serialized_end=344
  _globals['_SHELLWRITERESPONSE']._serialized_start=346
  _globals['_SHELLWRITERESPONSE']._serialized_end=455
  _globals['_SHELLRESIZEREQUEST']._serialized_start=457
  _globals['_SHELLRESIZEREQUEST']._serialized_end=526
  _globals['_SHELLRESIZERESPONSE']._serialized_start=528
  _globals['_SHELLRESIZERESPONSE']._serialized_end=643
  _globals['_SHELLCLOSEREQUEST']._serialized_start=645
  _globals['_SHELLCLOSEREQUEST']._serialized_end=685
  _globals['_SHELLCLOSERESPONSE']._serialized_start=687
  _globals['_SHELLCLOSERESPONSE']._serialized_end=789
# @@protoc_insertion_point(module_scope)
