/**
 * @file include/yunlink/c/abi/enums.h
 * @brief C ABI enum definitions.
 */

#ifndef YUNLINK_C_ABI_ENUMS_H
#define YUNLINK_C_ABI_ENUMS_H

#include "yunlink/c/abi/base.h"

typedef enum yunlink_result {
    YUNLINK_RESULT_OK = 0,
    YUNLINK_RESULT_INVALID_ARGUMENT = 1,
    YUNLINK_RESULT_SOCKET_ERROR = 2,
    YUNLINK_RESULT_BIND_ERROR = 3,
    YUNLINK_RESULT_LISTEN_ERROR = 4,
    YUNLINK_RESULT_CONNECT_ERROR = 5,
    YUNLINK_RESULT_TIMEOUT = 6,
    YUNLINK_RESULT_ENCODE_ERROR = 7,
    YUNLINK_RESULT_DECODE_ERROR = 8,
    YUNLINK_RESULT_CHECKSUM_MISMATCH = 9,
    YUNLINK_RESULT_INVALID_HEADER = 10,
    YUNLINK_RESULT_RUNTIME_STOPPED = 11,
    YUNLINK_RESULT_PROTOCOL_MISMATCH = 12,
    YUNLINK_RESULT_UNAUTHORIZED = 13,
    YUNLINK_RESULT_REJECTED = 14,
    YUNLINK_RESULT_INTERNAL = 15,
    YUNLINK_RESULT_NOT_FOUND = 100,
} yunlink_result_t;

typedef enum yunlink_transport {
    YUNLINK_TRANSPORT_TCP_SERVER = 1,
    YUNLINK_TRANSPORT_TCP_CLIENT = 2,
    YUNLINK_TRANSPORT_UDP_UNICAST = 3,
    YUNLINK_TRANSPORT_UDP_BROADCAST = 4,
    YUNLINK_TRANSPORT_UDP_MULTICAST = 5,
} yunlink_transport_t;

typedef enum yunlink_agent_type {
    YUNLINK_AGENT_TYPE_UNKNOWN = 0,
    YUNLINK_AGENT_TYPE_GROUND_STATION = 1,
    YUNLINK_AGENT_TYPE_UAV = 2,
    YUNLINK_AGENT_TYPE_UGV = 3,
    YUNLINK_AGENT_TYPE_SWARM_CONTROLLER = 4,
} yunlink_agent_type_t;

typedef enum yunlink_role {
    YUNLINK_ROLE_UNKNOWN = 0,
    YUNLINK_ROLE_OBSERVER = 1,
    YUNLINK_ROLE_CONTROLLER = 2,
    YUNLINK_ROLE_VEHICLE = 3,
    YUNLINK_ROLE_RELAY = 4,
} yunlink_role_t;

typedef enum yunlink_target_scope {
    YUNLINK_TARGET_SCOPE_ENTITY = 1,
    YUNLINK_TARGET_SCOPE_GROUP = 2,
    YUNLINK_TARGET_SCOPE_BROADCAST = 3,
} yunlink_target_scope_t;

typedef enum yunlink_control_source {
    YUNLINK_CONTROL_SOURCE_UNKNOWN = 0,
    YUNLINK_CONTROL_SOURCE_GROUND_STATION = 1,
    YUNLINK_CONTROL_SOURCE_REMOTE_CONTROLLER = 2,
    YUNLINK_CONTROL_SOURCE_TERMINAL = 3,
    YUNLINK_CONTROL_SOURCE_AUTONOMY = 4,
} yunlink_control_source_t;

typedef enum yunlink_authority_state {
    YUNLINK_AUTHORITY_STATE_OBSERVER = 0,
    YUNLINK_AUTHORITY_STATE_PENDING_GRANT = 1,
    YUNLINK_AUTHORITY_STATE_CONTROLLER = 2,
    YUNLINK_AUTHORITY_STATE_PREEMPTING = 3,
    YUNLINK_AUTHORITY_STATE_REVOKED = 4,
    YUNLINK_AUTHORITY_STATE_RELEASED = 5,
    YUNLINK_AUTHORITY_STATE_REJECTED = 6,
} yunlink_authority_state_t;

typedef enum yunlink_command_phase {
    YUNLINK_COMMAND_PHASE_RECEIVED = 1,
    YUNLINK_COMMAND_PHASE_ACCEPTED = 2,
    YUNLINK_COMMAND_PHASE_IN_PROGRESS = 3,
    YUNLINK_COMMAND_PHASE_SUCCEEDED = 4,
    YUNLINK_COMMAND_PHASE_FAILED = 5,
    YUNLINK_COMMAND_PHASE_CANCELLED = 6,
    YUNLINK_COMMAND_PHASE_EXPIRED = 7,
} yunlink_command_phase_t;

typedef enum yunlink_command_kind {
    YUNLINK_COMMAND_KIND_UNKNOWN = 0,
    YUNLINK_COMMAND_KIND_TAKEOFF = 1,
    YUNLINK_COMMAND_KIND_LAND = 2,
    YUNLINK_COMMAND_KIND_RETURN = 3,
    YUNLINK_COMMAND_KIND_GOTO = 4,
    YUNLINK_COMMAND_KIND_VELOCITY_SETPOINT = 5,
    YUNLINK_COMMAND_KIND_TRAJECTORY_CHUNK = 6,
    YUNLINK_COMMAND_KIND_FORMATION_TASK = 7,
} yunlink_command_kind_t;

typedef enum yunlink_session_state {
    YUNLINK_SESSION_STATE_DISCOVERED = 1,
    YUNLINK_SESSION_STATE_HANDSHAKING = 2,
    YUNLINK_SESSION_STATE_AUTHENTICATED = 3,
    YUNLINK_SESSION_STATE_NEGOTIATED = 4,
    YUNLINK_SESSION_STATE_ACTIVE = 5,
    YUNLINK_SESSION_STATE_DRAINING = 6,
    YUNLINK_SESSION_STATE_CLOSED = 7,
    YUNLINK_SESSION_STATE_LOST = 8,
    YUNLINK_SESSION_STATE_INVALID = 9,
} yunlink_session_state_t;

typedef enum yunlink_vehicle_event_kind {
    YUNLINK_VEHICLE_EVENT_KIND_INFO = 1,
    YUNLINK_VEHICLE_EVENT_KIND_TAKEOFF = 2,
    YUNLINK_VEHICLE_EVENT_KIND_LANDING = 3,
    YUNLINK_VEHICLE_EVENT_KIND_RETURN_HOME = 4,
    YUNLINK_VEHICLE_EVENT_KIND_FORMATION_UPDATE = 5,
    YUNLINK_VEHICLE_EVENT_KIND_FAULT = 6,
} yunlink_vehicle_event_kind_t;

typedef enum yunlink_runtime_event_type {
    YUNLINK_RUNTIME_EVENT_NONE = 0,
    YUNLINK_RUNTIME_EVENT_LINK = 1,
    YUNLINK_RUNTIME_EVENT_ERROR = 2,
    YUNLINK_RUNTIME_EVENT_COMMAND_RESULT = 3,
    YUNLINK_RUNTIME_EVENT_VEHICLE_CORE_STATE = 4,
    YUNLINK_RUNTIME_EVENT_VEHICLE_EVENT = 5,
    YUNLINK_RUNTIME_EVENT_FEATURE_LIST = 6,
    YUNLINK_RUNTIME_EVENT_FEATURE_GET = 7,
    YUNLINK_RUNTIME_EVENT_PX4_STATE = 8,
    YUNLINK_RUNTIME_EVENT_AUTHORITY_STATUS = 9,
} yunlink_runtime_event_type_t;

typedef enum yunlink_config_value_type {
    YUNLINK_CONFIG_VALUE_BOOL = 1,
    YUNLINK_CONFIG_VALUE_INT64 = 2,
    YUNLINK_CONFIG_VALUE_DOUBLE = 3,
    YUNLINK_CONFIG_VALUE_STRING = 4,
    YUNLINK_CONFIG_VALUE_STRING_LIST = 5,
    YUNLINK_CONFIG_VALUE_DOUBLE_LIST = 6,
} yunlink_config_value_type_t;

typedef enum yunlink_config_status {
    YUNLINK_CONFIG_STATUS_OK = 0,
    YUNLINK_CONFIG_STATUS_NOT_FOUND = 1,
    YUNLINK_CONFIG_STATUS_UNSUPPORTED = 2,
    YUNLINK_CONFIG_STATUS_UNAUTHENTICATED = 3,
    YUNLINK_CONFIG_STATUS_UNAUTHORIZED = 4,
    YUNLINK_CONFIG_STATUS_CONFLICT = 5,
    YUNLINK_CONFIG_STATUS_INVALID = 6,
    YUNLINK_CONFIG_STATUS_UNSAFE_STATE = 7,
    YUNLINK_CONFIG_STATUS_INTERNAL_ERROR = 8,
} yunlink_config_status_t;

typedef enum yunlink_config_apply_requirement {
    YUNLINK_CONFIG_APPLY_NONE = 0,
    YUNLINK_CONFIG_APPLY_COMPONENT_RESTART = 1,
    YUNLINK_CONFIG_APPLY_ENDPOINT_RESTART = 2,
    YUNLINK_CONFIG_APPLY_DEVICE_REBOOT = 3,
    YUNLINK_CONFIG_APPLY_MANUAL = 4,
} yunlink_config_apply_requirement_t;

typedef enum yunlink_config_apply_outcome {
    YUNLINK_CONFIG_OUTCOME_APPLIED = 1,
    YUNLINK_CONFIG_OUTCOME_RESTART_SCHEDULED = 2,
    YUNLINK_CONFIG_OUTCOME_MANUAL_ACTION_REQUIRED = 3,
    YUNLINK_CONFIG_OUTCOME_FAILED = 4,
} yunlink_config_apply_outcome_t;

#endif  // YUNLINK_C_ABI_ENUMS_H
