# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: org.yunlink.telemetry/v1/telemetry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'org.yunlink.telemetry/v1/telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(org.yunlink.telemetry/v1/telemetry.proto\x12\x18org.yunlink.telemetry.v1\"\x85\x01\n\x0bMetricValue\x12\x14\n\nbool_value\x18\x01 \x01(\x08H\x00\x12\x13\n\tint_value\x18\x02 \x01(\x12H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x14\n\nenum_token\x18\x04 \x01(\tH\x00\x12\x14\n\ntext_value\x18\x05 \x01(\tH\x00\x42\x07\n\x05value\"\xb0\x01\n\x06Metric\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.org.yunlink.telemetry.v1.MetricValue\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x38\n\x07quality\x18\x04 \x01(\x0e\x32\'.org.yunlink.telemetry.v1.MetricQuality\x12\x1b\n\x13source_timestamp_ns\x18\x05 \x01(\x04\"]\n\x0fSummarySnapshot\x12\x17\n\x0fgenerated_at_ns\x18\x01 \x01(\x04\x12\x31\n\x07metrics\x18\x02 \x03(\x0b\x32 .org.yunlink.telemetry.v1.Metric*\x7f\n\rMetricQuality\x12\x1e\n\x1aMETRIC_QUALITY_UNSPECIFIED\x10\x00\x12\x10\n\x0cMETRIC_VALID\x10\x01\x12\x10\n\x0cMETRIC_STALE\x10\x02\x12\x12\n\x0eMETRIC_INVALID\x10\x03\x12\x16\n\x12METRIC_UNAVAILABLE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'org.yunlink.telemetry.v1.telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICQUALITY']._serialized_start=480
  _globals['_METRICQUALITY']._serialized_end=607
  _globals['_METRICVALUE']._serialized_start=71
  _globals['_METRICVALUE']._serialized_end=204
  _globals['_METRIC']._serialized_start=207
  _globals['_METRIC']._serialized_end=383
  _globals['_SUMMARYSNAPSHOT']._serialized_start=385
  _globals['_SUMMARYSNAPSHOT']._serialized_end=478
# @@protoc_insertion_point(module_scope)
