# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: org.yunlink.system/v1/system.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'org.yunlink.system/v1/system.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"org.yunlink.system/v1/system.proto\x12\x15org.yunlink.system.v1\"8\n\x10\x43lockSyncRequest\x12\x14\n\x0cunix_time_ms\x18\x01 \x01(\x04\x12\x0e\n\x06source\x18\x02 \x01(\t\"\xa9\x01\n\x11\x43lockSyncResponse\x12\x34\n\x05\x65rror\x18\x01 \x01(\x0e\x32%.org.yunlink.system.v1.ClockSyncError\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1d\n\x15previous_unix_time_ms\x18\x03 \x01(\x04\x12\x1c\n\x14\x61pplied_unix_time_ms\x18\x04 \x01(\x04\x12\x10\n\x08\x64\x65lta_ms\x18\x05 \x01(\x03*\xdc\x01\n\x0e\x43lockSyncError\x12\x1a\n\x16\x43LOCK_SYNC_UNSPECIFIED\x10\x00\x12\x11\n\rCLOCK_SYNC_OK\x10\x01\x12\x1e\n\x1a\x43LOCK_SYNC_INVALID_REQUEST\x10\x02\x12\x1c\n\x18\x43LOCK_SYNC_ARMED_BLOCKED\x10\x03\x12\x1b\n\x17\x43LOCK_SYNC_OUT_OF_RANGE\x10\x04\x12!\n\x1d\x43LOCK_SYNC_HELPER_UNAVAILABLE\x10\x05\x12\x1d\n\x19\x43LOCK_SYNC_INTERNAL_ERROR\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'org.yunlink.system.v1.system_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLOCKSYNCERROR']._serialized_start=292
  _globals['_CLOCKSYNCERROR']._serialized_end=512
  _globals['_CLOCKSYNCREQUEST']._serialized_start=61
  _globals['_CLOCKSYNCREQUEST']._serialized_end=117
  _globals['_CLOCKSYNCRESPONSE']._serialized_start=120
  _globals['_CLOCKSYNCRESPONSE']._serialized_end=289
# @@protoc_insertion_point(module_scope)
